---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.19
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.19
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.19
labels:
  org.opencontainers.image.title: "Open WebUI"
  org.opencontainers.image.description: "Open WebUI for Local AI Models"
  org.opencontainers.image.source: "https://github.com/open-webui/open-webui"
  org.opencontainers.image.licenses: "MIT"
codenotary:
  base_image: codenotary@frenck.dev
  signer: vilabs-prox@home.local
