# Example configuration for Open WebUI Add-on

# Basic Configuration
log_level: info
ollama_base_url: "http://supervisor:11434"  # Default for Ollama add-on
enable_signup: true
enable_login_form: true

# Optional: Set a custom secret key (leave empty for auto-generation)
webui_secret_key: ""

# Optional: Default models to load (comma-separated)
default_models: ""

# Web Search Configuration
enable_web_search: false
web_search_engine: "duckduckgo"

# Image Generation Configuration
enable_image_generation: false
automatic_1111_base_url: ""  # http://your-automatic1111-instance:7860
comfyui_base_url: ""         # http://your-comfyui-instance:8188

# OpenAI API Configuration
openai_api_base_url: ""      # For OpenAI-compatible APIs
openai_api_key: ""           # Your API key

# Model Filtering
enable_model_filter: false
model_filter_list: ""        # Comma-separated list of models to show

# Advanced Configuration Examples:

# For production use (disable signup after initial setup):
# enable_signup: false

# For specific models only:
# enable_model_filter: true
# model_filter_list: "llama2,codellama,mistral"

# For integration with external APIs:
# openai_api_base_url: "https://api.openai.com/v1"
# openai_api_key: "your-openai-api-key-here"

# For web search capabilities:
# enable_web_search: true
# web_search_engine: "duckduckgo"
