---
# Markdown lint rules
rules:
  # Line length
  MD013:
    line_length: 120
    code_blocks: false
    tables: false
    headings: false

  # Multiple headers with the same content
  MD024:
    allow_different_nesting: true

  # Multiple top level headers in the same document
  MD025: false

  # First line in file should be a top level header
  MD041: false

  # Proper names should have the correct capitalization
  MD044:
    names:
      - Home Assistant
      - GitHub
      - Docker
      - YAML
      - JSON
