---
name: 🐛 Bug Report
about: Create a report to help us improve
title: '🐛 [ADD-ON NAME] - Brief description of the bug'
labels: ["bug", "needs-triage"]
assignees: []

---

## Bug Report

### Add-on
**Add-on name:** (e.g., Open WebUI)
**Add-on version:** (e.g., 1.0.0)

### Environment
**Home Assistant version:** (e.g., 2024.1.0)
**Home Assistant installation type:** (e.g., Home Assistant OS, Container, Core)
**Architecture:** (e.g., amd64, aarch64, armv7)

### Expected Behavior
A clear and concise description of what you expected to happen.

### Actual Behavior
A clear and concise description of what actually happened.

### Steps to Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Screenshots
If applicable, add screenshots to help explain your problem.

### Logs
```
Please include relevant log entries here. You can find logs in:
- Home Assistant: Settings -> Add-ons -> [Add-on name] -> Log tab
- System logs: Settings -> System -> Logs
```

### Configuration
```yaml
# Please include your add-on configuration (remove sensitive information)
```

### Additional Context
Add any other context about the problem here.

### Checklist
- [ ] I have read the add-on documentation
- [ ] I have checked the logs for error messages
- [ ] I have searched for similar issues
- [ ] This issue is specific to this add-on (not a general Home Assistant issue)
