---
name: 🚀 Feature Request
about: Suggest an idea for this project
title: '🚀 [ADD-ON NAME] - Brief description of the feature'
labels: ["enhancement", "needs-triage"]
assignees: []

---

## Feature Request

### Add-on
**Add-on name:** (e.g., Open WebUI)

### Is your feature request related to a problem?
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the solution you'd like
A clear and concise description of what you want to happen.

### Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.

### Additional Context
Add any other context, screenshots, or examples about the feature request here.

### Checklist
- [ ] I have searched for similar feature requests
- [ ] This feature would be useful for other users
- [ ] This feature is within the scope of this add-on
